// elements
export default {
  headerElement: document.querySelector('h1'),
  leadElement: document.querySelector('p.lead'),
  formElement: document.querySelector('form.rss-form'),
  inputElement: document.querySelector('input#url-input'),
  inputLabelElement: document.querySelector('label'),
  submitButton: document.querySelector('form button'),
  exampleElement: document.querySelector('p.example'),
  messageElement: document.querySelector('p.feedback'),
  feedsHeader: document.querySelector('h2.feeds__header'),
  postsHeader: document.querySelector('h2.posts__header'),
  feedListElement: document.querySelector('ul.feeds__list'),
  postsListElement: document.querySelector('ul.posts__list'),
  footerCreatedElement: document.querySelector('div.copyright'),
  authorLinkElement: document.querySelector('a.author'),
  modalHeader: document.querySelector('.modal-title'),
  modalTextElement: document.querySelector('.modal-body'),
  modalReadArticleLink: document.querySelector('.modal-footer > a'),
  modalCloseButton: document.querySelector('.modal-footer > button'),
};
