// elements
export const headerElement = document.querySelector('h1');
export const leadElement = document.querySelector('p.lead');
export const formElement = document.querySelector('form.rss-form');
export const inputElement = formElement.querySelector('input#url-input');
export const inputLabelElement = document.querySelector('label');
export const submitButton = document.querySelector('form button');
export const exampleElement = document.querySelector('p.example');
export const messageElement = document.querySelector('p.feedback');
export const feedsHeader = document.querySelector('h2.feeds__header');
export const postsHeader = document.querySelector('h2.posts__header');
export const feedListElement = document.querySelector('ul.feeds__list');
export const postsListElement = document.querySelector('ul.posts__list');
export const footerCreatedElement = document.querySelector('div.copyright');
export const authorLinkElement = document.querySelector('a.author');
export const modalHeader = document.querySelector('.modal-title');
export const modalTextElement = document.querySelector('.modal-body');
export const modalReadArticleLink = document.querySelector('.modal-footer > a');
export const modalCloseButton = document.querySelector('.modal-footer > button');
